site_name: Louis Rossignol
site_url: https://louis_rsgl.github.io/researchwebsite/ # must have the trailing slash
site_author: Louis Rossignol (louis.rossignol@mail.mcgill.ca)
site_description: Research site of Louis Rossignol
copyright: > 
  &copy; 2024 Louis Rossignol <br>
  <a href="https://github.com/vuquangtrong/mkdocs-material-blog">Blog Theme</a> /
  <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>



theme:
    name: material
    palette:
      - scheme: default
        primary: marroon
        accent : orange
        
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    features:
    - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.sections # sections are rendered as groups in the sidebar
    - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    - toc.integrate # show table of contents to navigation panel
    - header.autohide
    - content.code.annotate 
    - content.code.copy

extra_javascript:
  
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Research: research/index.md
  - Outreach: outreach/index.md
  - About Me: about/index.md

markdown_extensions:
  - attr_list   # For adding attributes such as right/left align to images
  - md_in_html  # Using Figures



# Additional plugins
plugins:
    - search
    # Using jupyter notebook  
    - mkdocs-jupyter:
          theme: default

